# .cz.toml
[tool.commitizen]

[tool.commitizen.workspace]
# Defines which projects are part of the monorepo
members = ["lib/python", "spec"]


# Config for the Python library
[tool.commitizen.files."lib/python"]
version_files = [
    "lib/python/src/questfoundry/version.py:__version__",
    "lib/python/pyproject.toml:version"
]
tag_format = "v$version"

# Config for the unified Specification
[tool.commitizen.files."spec"]
version_files = [
    "spec/SPEC_VERSION.txt:version"
]
tag_format = "spec-v$version"
