"""Generated file warning banner.

This module contains the warning banner prepended to all generated files.
Separated to avoid circular imports between generators/__init__.py and
the individual generator modules.
"""

# =============================================================================
# Generated File Warning Banner
# =============================================================================
# This warning is prepended to all generated files to prevent accidental edits.
# The pattern has been: developers edit generated/ files directly, then those
# changes get overwritten by `qf compile`. This wastes time and causes bugs.

GENERATED_FILE_WARNING = """
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                                                                           ║
# ║   ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗   ║
# ║   ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗  ║
# ║   ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║  ║
# ║   ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║  ║
# ║   ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ███████╗██████╔╝  ║
# ║   ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝   ║
# ║                                                                           ║
# ║   IT    ██╗████████╗    ██╗                                               ║
# ║         ██║╚══██╔══╝    ██║                                               ║
# ║         ██║   ██║       ██║                                               ║
# ║         ██║   ██║       ╚═╝                                               ║
# ║         ██║   ██║       ██╗                                               ║
# ║         ╚═╝   ╚═╝       ╚═╝                                               ║
# ║                                                                           ║
# ╠═══════════════════════════════════════════════════════════════════════════╣
# ║  This file is AUTO-GENERATED by the QuestFoundry compiler.                ║
# ║                                                                           ║
# ║  ANY CHANGES YOU MAKE HERE WILL BE LOST when you run `qf compile`.        ║
# ║                                                                           ║
# ║  To make changes:                                                         ║
# ║    1. Edit the source file in src/questfoundry/domain/                    ║
# ║    2. Run: qf compile                                                     ║
# ║    3. Your changes will appear here                                       ║
# ║                                                                           ║
# ║  Source mapping:                                                          ║
# ║    domain/roles/*.md      → generated/roles/*.py                          ║
# ║    domain/ontology/*.md   → generated/models/*.py                         ║
# ║                                                                           ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
"""
