"""Role code generator - transforms role definitions to Python configurations.

This module generates Python code from parsed role definitions. It reads
role-meta, role-tools, role-constraints, and role-prompt directives and
produces RoleConfig dataclasses for runtime use.

Architecture
------------
The generator produces:

1. **roles/__init__.py**: Re-exports all role configurations
2. **roles/{role_id}.py**: Individual RoleConfig for each role

The generated code is written to ``generated/roles/`` and is intended to be
checked into version control for easier debugging and IDE support.

Example Usage
-------------
Generate role configs from parsed IR::

    from questfoundry.compiler.generators.roles import generate_roles
    from questfoundry.compiler.models import RoleIR

    roles = {"showrunner": showrunner_ir, "plotwright": plotwright_ir}
    result = generate_roles(roles, "src/questfoundry/generated/roles")

    print(f"Generated: {list(result.keys())}")
    # Generated: ['showrunner.py', 'plotwright.py', '__init__.py']

See Also
--------
:mod:`questfoundry.compiler.parser` : Source parsing
:mod:`questfoundry.compiler.models.ir` : IR definitions
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from questfoundry.compiler.models import RoleIR


def _class_name(name: str) -> str:
    """Convert an identifier to PascalCase class name.

    Parameters
    ----------
    name : str
        The original identifier (snake_case or kebab-case).

    Returns
    -------
    str
        PascalCase class name.
    """
    parts = re.split(r"[_-]", name)
    return "".join(part.capitalize() for part in parts)


def _escape_string(s: str) -> str:
    """Escape a string for use in Python source code."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _escape_multiline(s: str) -> str:
    """Escape a string for triple-quoted Python strings."""
    return s.replace('"""', '\\"\\"\\"')


def generate_role_code(role: RoleIR) -> str:
    """Generate Python code for a single role configuration.

    Creates a module with a RoleConfig dataclass instance.

    Parameters
    ----------
    role : RoleIR
        The role IR to generate code for.

    Returns
    -------
    str
        Complete Python module source code.
    """
    cls_name = _class_name(role.id)

    lines = [
        f'"""Generated role configuration for {role.id}.',
        "",
        "DO NOT EDIT - This file is auto-generated by the QuestFoundry compiler.",
        '"""',
        "",
        "from questfoundry.compiler.models import Agency, RoleIR, RoleToolIR",
        "",
        "",
    ]

    # Generate the RoleConfig constant
    lines.append(f"{cls_name.upper()} = RoleIR(")
    lines.append(f'    id="{role.id}",')
    lines.append(f'    abbr="{role.abbr}",')
    lines.append(f'    archetype="{_escape_string(role.archetype)}",')
    lines.append(f"    agency=Agency.{role.agency.name},")
    lines.append(f'    mandate="{_escape_string(role.mandate)}",')

    # Tools
    if role.tools:
        lines.append("    tools=[")
        for tool in role.tools:
            lines.append(
                f'        RoleToolIR(name="{tool.name}", description="{_escape_string(tool.description)}"),'
            )
        lines.append("    ],")
    else:
        lines.append("    tools=[],")

    # Constraints
    if role.constraints:
        lines.append("    constraints=[")
        for constraint in role.constraints:
            lines.append(f'        "{_escape_string(constraint)}",')
        lines.append("    ],")
    else:
        lines.append("    constraints=[],")

    # Prompt template (multiline)
    if role.prompt_template:
        escaped = _escape_multiline(role.prompt_template)
        lines.append(f'    prompt_template="""{escaped}""",')
    else:
        lines.append('    prompt_template="",')

    lines.append(")")
    lines.append("")

    # Add docstring
    lines.append(f'"""{cls_name} role configuration.')
    lines.append("")
    lines.append(f"Archetype: {role.archetype}")
    lines.append(f"Agency: {role.agency.value}")
    lines.append(f'Mandate: "{role.mandate}"')
    if role.tools:
        lines.append("")
        lines.append("Tools:")
        for tool in role.tools:
            lines.append(f"- {tool.name}: {tool.description}")
    lines.append('"""')
    lines.append("")

    return "\n".join(lines)


def generate_roles_init(roles: Mapping[str, RoleIR]) -> str:
    """Generate __init__.py for the roles package.

    Re-exports all role configurations for convenient importing.

    Parameters
    ----------
    roles : Mapping[str, RoleIR]
        Dictionary of role ID to RoleIR.

    Returns
    -------
    str
        Complete Python module source code.
    """
    lines = [
        '"""Generated role configurations from domain/roles/*.md.',
        "",
        "DO NOT EDIT - This file is auto-generated by the QuestFoundry compiler.",
        '"""',
        "",
    ]

    # Imports
    for role_id in sorted(roles.keys()):
        cls_name = _class_name(role_id)
        lines.append(f"from questfoundry.generated.roles.{role_id} import {cls_name.upper()}")

    lines.append("")

    # __all__
    lines.append("__all__ = [")
    for role_id in sorted(roles.keys()):
        cls_name = _class_name(role_id)
        lines.append(f'    "{cls_name.upper()}",')
    lines.append("]")

    # ALL_ROLES dict for runtime lookup
    lines.append("")
    lines.append("# All roles indexed by ID")
    lines.append("ALL_ROLES = {")
    for role_id in sorted(roles.keys()):
        cls_name = _class_name(role_id)
        lines.append(f'    "{role_id}": {cls_name.upper()},')
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def generate_roles(
    roles: Mapping[str, RoleIR],
    output_dir: str | Path,
) -> dict[str, Path]:
    """Generate Python role configurations from role IR.

    Creates individual role files and an __init__.py in the output directory.

    Parameters
    ----------
    roles : Mapping[str, RoleIR]
        Dictionary of role ID to RoleIR.
    output_dir : str | Path
        Directory to write generated files.

    Returns
    -------
    dict[str, Path]
        Dictionary mapping filename to full path of generated files.

    Raises
    ------
    OSError
        If output directory cannot be created or files cannot be written.

    Examples
    --------
    Generate roles from IR::

        from questfoundry.compiler.generators.roles import generate_roles

        result = generate_roles(
            roles=domain_ir.roles,
            output_dir="src/questfoundry/generated/roles"
        )

        print(f"Generated: {list(result.keys())}")
        # Generated: ['showrunner.py', 'plotwright.py', '__init__.py']
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    generated: dict[str, Path] = {}

    # Generate individual role files
    for role_id, role_ir in sorted(roles.items()):
        role_code = generate_role_code(role_ir)
        role_file = output_path / f"{role_id}.py"
        role_file.write_text(role_code)
        generated[f"{role_id}.py"] = role_file

    # Generate __init__.py
    init_code = generate_roles_init(roles)
    init_file = output_path / "__init__.py"
    init_file.write_text(init_code)
    generated["__init__.py"] = init_file

    return generated
