"""Generated Pydantic models from JSON Schema.

DO NOT EDIT THIS FILE DIRECTLY.

This file is auto-generated by scripts/generate_models.py from the JSON Schema
files in schemas/. To modify artifact structure:

1. Edit the JSON Schema in schemas/
2. Run: uv run python scripts/generate_models.py
3. Commit both the schema and this generated file

Source of truth: schemas/*.schema.json
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel

# --- Models from dream.schema.json ---


class ToneItem(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Theme(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Scope(BaseModel):
    target_word_count: Annotated[
        int | None, Field(description="Approximate final length", ge=1000)
    ] = None
    estimated_passages: Annotated[int | None, Field(description="Target scene count", ge=5)] = None
    branching_depth: Annotated[
        str | None,
        Field(
            description="Branching complexity (e.g., light, moderate, heavy, extensive)",
            min_length=1,
        ),
    ] = None
    estimated_playtime_minutes: Annotated[
        int | None, Field(description="Target reading time", ge=1)
    ] = None


class Include(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Exclude(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class ContentNotes(BaseModel):
    includes: Annotated[list[Include] | None, Field(description="Content included")] = None
    excludes: Annotated[list[Exclude] | None, Field(description="Content excluded")] = None


class DreamArtifact(BaseModel):
    type: Annotated[Literal["dream"], Field(description="Artifact type identifier")]
    version: Annotated[int, Field(description="Schema version number", ge=1)]
    genre: Annotated[str, Field(description="Primary genre", min_length=1)]
    subgenre: Annotated[
        str | None, Field(description="Optional genre refinement", min_length=1)
    ] = None
    tone: Annotated[list[ToneItem], Field(description="Tone descriptors", min_length=1)]
    audience: Annotated[
        str,
        Field(
            description="Target audience (e.g., adult, young adult, all ages, mature)",
            min_length=1,
        ),
    ]
    themes: Annotated[list[Theme], Field(description="Thematic elements", min_length=1)]
    style_notes: Annotated[str | None, Field(description="Style guidance", min_length=1)] = None
    scope: Scope | None = None
    content_notes: ContentNotes | None = None
