"""Auto-generated Pydantic models from JSON Schema.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! DO NOT EDIT THIS FILE DIRECTLY - IT IS AUTO-GENERATED                      !!
!! Source of truth: schemas/*.schema.json                                      !!
!! Run: uv run python scripts/generate_models.py                               !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

SCHEMA-FIRST WORKFLOW:
1. Edit the JSON Schema file (e.g., schemas/dream.schema.json)
2. Run the generator: uv run python scripts/generate_models.py
3. Commit BOTH the schema AND this generated file

The JSON Schema is the SINGLE SOURCE OF TRUTH. If you need to change
the model structure, change the schema first. Never modify this file.

Optional vs Nullable:
- Optional fields (not in "required") may be absent - we default to None
- Nullable fields (type: ["integer", "null"]) explicitly accept null values
- LLMs often send null for optional fields; use strip_null_values() before validation
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field, StringConstraints


class ContentNotes(BaseModel):
    """Content advisory notes for inclusions and exclusions"""

    excludes: list[Annotated[str, StringConstraints(min_length=1)]] = Field(
        default_factory=list, description="Content excluded"
    )
    includes: list[Annotated[str, StringConstraints(min_length=1)]] = Field(
        default_factory=list, description="Content included"
    )


class Scope(BaseModel):
    """Scope model."""

    branching_depth: str = Field(
        default="moderate",
        description="Branching complexity (e.g., light, moderate, heavy, extensive)",
        min_length=1,
    )
    estimated_passages: int = Field(description="Target scene count", ge=5)
    estimated_playtime_minutes: int | None = Field(
        default=None, description="Target reading time", ge=1
    )
    target_word_count: int = Field(description="Approximate final length", ge=1000)


class DreamArtifact(BaseModel):
    """DREAM Artifact - Creative vision and constraints for the story"""

    audience: str = Field(
        description="Target audience (e.g., adult, young adult, all ages, mature)", min_length=1
    )
    content_notes: ContentNotes | None = Field(
        default=None, description="Content advisory notes for inclusions and exclusions"
    )
    genre: str = Field(description="Primary genre", min_length=1)
    scope: Scope | None = Field(default=None)
    style_notes: str | None = Field(default=None, description="Style guidance", min_length=1)
    subgenre: str | None = Field(
        default=None, description="Optional genre refinement", min_length=1
    )
    themes: list[Annotated[str, StringConstraints(min_length=1)]] = Field(
        description="Thematic elements", min_length=1
    )
    tone: list[Annotated[str, StringConstraints(min_length=1)]] = Field(
        description="Tone descriptors", min_length=1
    )
    type: Literal["dream"] = "dream"
    version: int = Field(default=1, description="Schema version number", ge=1)


# Type alias for artifact types
ArtifactType = DreamArtifact
