"""Pydantic models for stage outputs.

These models define the structured output format for each pipeline stage.
The LLM produces output matching these schemas, which is then validated
and applied to the unified graph.

The ontology (node types, relationships, lifecycle) is defined in
docs/design/00-spec.md. These models are implementations of that ontology.

Terminology (v5):
- dilemma: Binary dramatic questions
- path: Routes exploring specific answers to dilemmas
- answer: Possible resolutions to dilemmas
- intersection: Beats serving multiple paths
"""

from questfoundry.models.brainstorm import (
    Answer,
    BrainstormOutput,
    Dilemma,
    Entity,
    EntityType,
)
from questfoundry.models.dream import (
    ContentNotes,
    DreamArtifact,
    Scope,
)
from questfoundry.models.dress import (
    ArtDirection,
    BatchedBriefItem,
    BatchedBriefOutput,
    BatchedCodexItem,
    BatchedCodexOutput,
    CodexEntry,
    DressPhase0Output,
    DressPhase1Output,
    DressPhase2Output,
    DressPhaseResult,
    DressResult,
    EntityVisual,
    EntityVisualWithId,
    Illustration,
    IllustrationBrief,
    IllustrationCategory,
)
from questfoundry.models.fill import (
    BatchedExpandOutput,
    EntityUpdate,
    ExpandBlueprint,
    FillExtractOutput,
    FillPassageOutput,
    FillPhase0Output,
    FillPhase1Output,
    FillPhase2Output,
    FillPhaseResult,
    FillResult,
    ReviewFlag,
    SpokeLabelUpdate,
    VoiceDocument,
)
from questfoundry.models.grow import (
    Arc,
    AtmosphericDetail,
    Choice,
    ChoiceLabel,
    EntityArcDescriptor,
    EntityOverlay,
    ForkProposal,
    GapProposal,
    GrowPhaseResult,
    GrowResult,
    HubProposal,
    IntersectionProposal,
    OverlayDetailItem,
    OverlayProposal,
    Passage,
    PathMiniArc,
    Phase3Output,
    Phase4aOutput,
    Phase4bOutput,
    Phase4dOutput,
    Phase4eOutput,
    Phase4fOutput,
    Phase8cOutput,
    Phase9bOutput,
    Phase9cOutput,
    Phase9Output,
    SceneTypeTag,
    SpokeLabelStyle,
    SpokeProposal,
    StateFlag,
)
from questfoundry.models.pipeline import PhaseResult
from questfoundry.models.polish import (
    ArcPivot,
    CharacterArcMetadata,
    ChoiceLabelItem,
    ChoiceSpec,
    FalseBranchCandidate,
    FalseBranchDecisionItem,
    FalseBranchSpec,
    MicroBeatProposal,
    PassageSpec,
    PolishResult,
    ReorderedSection,
    ResidueContentItem,
    ResidueSpec,
    VariantSpec,
    VariantSummaryItem,
)
from questfoundry.models.polish import (
    Phase1Output as PolishPhase1Output,
)
from questfoundry.models.polish import (
    Phase2Output as PolishPhase2Output,
)
from questfoundry.models.polish import (
    Phase3Output as PolishPhase3Output,
)
from questfoundry.models.polish import (
    Phase5aOutput as PolishPhase5aOutput,
)
from questfoundry.models.polish import (
    Phase5bOutput as PolishPhase5bOutput,
)
from questfoundry.models.polish import (
    Phase5cOutput as PolishPhase5cOutput,
)
from questfoundry.models.polish import (
    Phase5dOutput as PolishPhase5dOutput,
)
from questfoundry.models.seed import (
    Consequence,
    DilemmaAnalysis,
    DilemmaAnalysisSection,
    DilemmaDecision,
    DilemmaEffect,
    DilemmaImpact,
    DilemmaOrdering,
    DilemmaRelationship,
    DilemmaRelationshipsSection,
    DilemmaRole,
    EndingSalience,
    EntityDecision,
    EntityDisposition,
    InitialBeat,
    Path,
    PathTier,
    ResidueWeight,
    SeedOutput,
    TemporalHint,
    TemporalPosition,
)

__all__ = [
    "Answer",
    "Arc",
    "ArcPivot",
    "ArtDirection",
    "AtmosphericDetail",
    "BatchedBriefItem",
    "BatchedBriefOutput",
    "BatchedCodexItem",
    "BatchedCodexOutput",
    "BatchedExpandOutput",
    "BrainstormOutput",
    "CharacterArcMetadata",
    "Choice",
    "ChoiceLabel",
    "ChoiceLabelItem",
    "ChoiceSpec",
    "CodexEntry",
    "Consequence",
    "ContentNotes",
    "Dilemma",
    "DilemmaAnalysis",
    "DilemmaAnalysisSection",
    "DilemmaDecision",
    "DilemmaEffect",
    "DilemmaImpact",
    "DilemmaOrdering",
    "DilemmaRelationship",
    "DilemmaRelationshipsSection",
    "DilemmaRole",
    "DreamArtifact",
    "DressPhase0Output",
    "DressPhase1Output",
    "DressPhase2Output",
    "DressPhaseResult",
    "DressResult",
    "EndingSalience",
    "Entity",
    "EntityArcDescriptor",
    "EntityDecision",
    "EntityDisposition",
    "EntityOverlay",
    "EntityType",
    "EntityUpdate",
    "EntityVisual",
    "EntityVisualWithId",
    "ExpandBlueprint",
    "FalseBranchCandidate",
    "FalseBranchDecisionItem",
    "FalseBranchSpec",
    "FillExtractOutput",
    "FillPassageOutput",
    "FillPhase0Output",
    "FillPhase1Output",
    "FillPhase2Output",
    "FillPhaseResult",
    "FillResult",
    "ForkProposal",
    "GapProposal",
    "GrowPhaseResult",
    "GrowResult",
    "HubProposal",
    "Illustration",
    "IllustrationBrief",
    "IllustrationCategory",
    "InitialBeat",
    "IntersectionProposal",
    "MicroBeatProposal",
    "OverlayDetailItem",
    "OverlayProposal",
    "Passage",
    "PassageSpec",
    "Path",
    "PathMiniArc",
    "PathTier",
    "Phase3Output",
    "Phase4aOutput",
    "Phase4bOutput",
    "Phase4dOutput",
    "Phase4eOutput",
    "Phase4fOutput",
    "Phase8cOutput",
    "Phase9Output",
    "Phase9bOutput",
    "Phase9cOutput",
    "PhaseResult",
    "PolishPhase1Output",
    "PolishPhase2Output",
    "PolishPhase3Output",
    "PolishPhase5aOutput",
    "PolishPhase5bOutput",
    "PolishPhase5cOutput",
    "PolishPhase5dOutput",
    "PolishResult",
    "ReorderedSection",
    "ResidueContentItem",
    "ResidueSpec",
    "ResidueWeight",
    "ReviewFlag",
    "SceneTypeTag",
    "Scope",
    "SeedOutput",
    "SpokeLabelStyle",
    "SpokeLabelUpdate",
    "SpokeProposal",
    "StateFlag",
    "TemporalHint",
    "TemporalPosition",
    "VariantSpec",
    "VariantSummaryItem",
    "VoiceDocument",
]
