"""Pydantic models for stage outputs.

These models define the structured output format for each pipeline stage.
The LLM produces output matching these schemas, which is then validated
and applied to the unified graph.

The ontology (node types, relationships, lifecycle) is defined in
docs/design/00-spec.md. These models are implementations of that ontology.

Terminology (v5):
- dilemma: Binary dramatic questions
- path: Routes exploring specific answers to dilemmas
- answer: Possible resolutions to dilemmas
- intersection: Beats serving multiple paths
"""

from questfoundry.models.brainstorm import (
    Answer,
    BrainstormOutput,
    Dilemma,
    Entity,
    EntityType,
)
from questfoundry.models.dream import (
    ContentNotes,
    DreamArtifact,
    Scope,
)
from questfoundry.models.dress import (
    ArtDirection,
    CodexEntry,
    DressPhase0Output,
    DressPhase1Output,
    DressPhase2Output,
    DressPhaseResult,
    DressResult,
    EntityVisual,
    EntityVisualWithId,
    Illustration,
    IllustrationBrief,
    IllustrationCategory,
)
from questfoundry.models.fill import (
    EntityUpdate,
    FillExtractOutput,
    FillPassageOutput,
    FillPhase0Output,
    FillPhase1Output,
    FillPhase2Output,
    FillPhaseResult,
    FillResult,
    ReviewFlag,
    VoiceDocument,
)
from questfoundry.models.grow import (
    Arc,
    AtmosphericDetail,
    Choice,
    ChoiceLabel,
    Codeword,
    EntityOverlay,
    EntryMood,
    EntryStateBeat,
    GapProposal,
    GrowPhaseResult,
    GrowResult,
    IntersectionProposal,
    OverlayProposal,
    Passage,
    PathAgnosticAssessment,
    PathMiniArc,
    Phase2Output,
    Phase3Output,
    Phase4aOutput,
    Phase4bOutput,
    Phase4dOutput,
    Phase4eOutput,
    Phase8cOutput,
    Phase9Output,
    SceneTypeTag,
)
from questfoundry.models.pipeline import PhaseResult
from questfoundry.models.seed import (
    Consequence,
    ConvergenceSketch,
    DilemmaDecision,
    DilemmaEffect,
    DilemmaImpact,
    EntityDecision,
    EntityDisposition,
    InitialBeat,
    Path,
    PathTier,
    SeedOutput,
)

__all__ = [
    "Answer",
    "Arc",
    "ArtDirection",
    "AtmosphericDetail",
    "BrainstormOutput",
    "Choice",
    "ChoiceLabel",
    "Codeword",
    "CodexEntry",
    "Consequence",
    "ContentNotes",
    "ConvergenceSketch",
    "Dilemma",
    "DilemmaDecision",
    "DilemmaEffect",
    "DilemmaImpact",
    "DreamArtifact",
    "DressPhase0Output",
    "DressPhase1Output",
    "DressPhase2Output",
    "DressPhaseResult",
    "DressResult",
    "Entity",
    "EntityDecision",
    "EntityDisposition",
    "EntityOverlay",
    "EntityType",
    "EntityUpdate",
    "EntityVisual",
    "EntityVisualWithId",
    "EntryMood",
    "EntryStateBeat",
    "FillExtractOutput",
    "FillPassageOutput",
    "FillPhase0Output",
    "FillPhase1Output",
    "FillPhase2Output",
    "FillPhaseResult",
    "FillResult",
    "GapProposal",
    "GrowPhaseResult",
    "GrowResult",
    "Illustration",
    "IllustrationBrief",
    "IllustrationCategory",
    "InitialBeat",
    "IntersectionProposal",
    "OverlayProposal",
    "Passage",
    "Path",
    "PathAgnosticAssessment",
    "PathMiniArc",
    "PathTier",
    "Phase2Output",
    "Phase3Output",
    "Phase4aOutput",
    "Phase4bOutput",
    "Phase4dOutput",
    "Phase4eOutput",
    "Phase8cOutput",
    "Phase9Output",
    "PhaseResult",
    "ReviewFlag",
    "SceneTypeTag",
    "Scope",
    "SeedOutput",
    "VoiceDocument",
]
