#!/usr/bin/env python3
"""Generate Pydantic models from JSON Schema files.

This script generates Pydantic v2 models from the JSON Schema files in schemas/.
The generated models are written to src/questfoundry/artifacts/generated.py.

JSON Schemas are the source of truth for artifact structure. This ensures:
- File format is defined independently of code
- Pydantic models stay in sync with schemas
- Changes to schemas are reflected in models automatically

Usage:
    uv run python scripts/generate_models.py

The generated file should be committed to version control.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# Project root (parent of scripts/)
PROJECT_ROOT = Path(__file__).parent.parent
SCHEMAS_DIR = PROJECT_ROOT / "schemas"
OUTPUT_FILE = PROJECT_ROOT / "src" / "questfoundry" / "artifacts" / "generated.py"


def generate_models() -> int:
    """Generate Pydantic models from all JSON Schema files."""
    schema_files = list(SCHEMAS_DIR.glob("*.schema.json"))

    if not schema_files:
        print(f"No schema files found in {SCHEMAS_DIR}", file=sys.stderr)
        return 1

    print(f"Found {len(schema_files)} schema file(s):")
    for f in schema_files:
        print(f"  - {f.name}")

    # Generate models from each schema file and combine
    all_content: list[str] = []
    imports_seen: set[str] = set()

    for schema_file in schema_files:
        print(f"\nProcessing {schema_file.name}...")

        # Build datamodel-codegen command for single file
        cmd = [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(schema_file),
            "--input-file-type",
            "jsonschema",
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--use-annotated",
            "--field-constraints",
            "--collapse-root-models",  # Simplify RootModel[str] → str
            "--use-union-operator",  # Use X | Y instead of Union[X, Y]
            "--target-python-version",
            "3.11",
            "--use-double-quotes",
        ]

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, check=False)

            if result.returncode != 0:
                print(f"Error generating models from {schema_file}:\n{result.stderr}", file=sys.stderr)
                return result.returncode

            # Parse output to separate imports from models
            output = result.stdout
            lines = output.splitlines()

            in_imports = True
            model_lines: list[str] = []

            for line in lines:
                # Skip generated header comments
                if line.startswith("#"):
                    continue

                # Collect imports (deduplicate)
                if in_imports and (
                    line.startswith("from ") or line.startswith("import ") or line == ""
                ):
                    if line and line not in imports_seen:
                        imports_seen.add(line)
                    continue

                in_imports = False
                model_lines.append(line)

            if model_lines:
                # Add section comment
                all_content.append(f"\n# --- Models from {schema_file.name} ---\n")
                all_content.extend(model_lines)

        except FileNotFoundError:
            print(
                "datamodel-code-generator not found. Install with: uv pip install datamodel-code-generator",
                file=sys.stderr,
            )
            return 1

    print(f"\nWriting combined models to {OUTPUT_FILE}...")

    # Build final file content
    header = '''"""Generated Pydantic models from JSON Schema.

DO NOT EDIT THIS FILE DIRECTLY.

This file is auto-generated by scripts/generate_models.py from the JSON Schema
files in schemas/. To modify artifact structure:

1. Edit the JSON Schema in schemas/
2. Run: uv run python scripts/generate_models.py
3. Commit both the schema and this generated file

Source of truth: schemas/*.schema.json
"""

from __future__ import annotations

'''

    # Add sorted imports
    sorted_imports = sorted(imports_seen)
    imports_section = "\n".join(sorted_imports) + "\n"

    # Combine all content
    final_content = header + imports_section + "\n".join(all_content)

    # Ensure parent directory exists
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    # Write output
    OUTPUT_FILE.write_text(final_content)

    # Format with ruff
    try:
        subprocess.run(
            [sys.executable, "-m", "ruff", "format", str(OUTPUT_FILE)],
            capture_output=True,
            check=False,
        )
        subprocess.run(
            [sys.executable, "-m", "ruff", "check", "--fix", str(OUTPUT_FILE)],
            capture_output=True,
            check=False,
        )
    except Exception:
        print("Warning: Could not format with ruff", file=sys.stderr)

    print(f"\nGenerated models written to {OUTPUT_FILE}")
    print("\nRemember to commit both the schema changes and generated models!")
    return 0


if __name__ == "__main__":
    sys.exit(generate_models())
