"""
QuestFoundry Config Command - Configuration file generation and inspection.

Provides:
- Generate default configuration files (YAML/TOML)
- Dump current configuration (with resolved env vars)
- Output to stdout or file
"""

from pathlib import Path
from typing import Any

import typer
from rich.console import Console

from questfoundry.runtime.config import (
    LLMConfig,
    LoggingConfig,
    MemoryConfig,
    NetworkConfig,
    PathsConfig,
    RuntimeConfig,
    get_settings,
)

console = Console()

# Create config subcommand group
config_app = typer.Typer(
    name="config",
    help="Configuration management commands",
    no_args_is_help=True,
)


def _model_to_dict(model: Any, include_defaults: bool = True) -> dict[str, Any]:
    """Convert a Pydantic model to a dictionary, optionally excluding defaults."""
    if hasattr(model, "model_dump"):
        return model.model_dump()
    return dict(model)


def _get_default_config() -> dict[str, Any]:
    """Get configuration with all default values."""
    return {
        "runtime": _model_to_dict(RuntimeConfig()),
        "llm": _model_to_dict(LLMConfig()),
        "memory": _model_to_dict(MemoryConfig()),
        "paths": _model_to_dict(PathsConfig()),
        "logging": _model_to_dict(LoggingConfig()),
        "network": _model_to_dict(NetworkConfig()),
    }


def _get_current_config(mask_secrets: bool = True) -> dict[str, Any]:
    """Get current configuration with resolved environment variables."""
    settings = get_settings()
    config = {
        "runtime": _model_to_dict(settings.runtime),
        "llm": _model_to_dict(settings.llm),
        "memory": _model_to_dict(settings.memory),
        "paths": _model_to_dict(settings.paths),
        "logging": _model_to_dict(settings.logging),
        "network": _model_to_dict(settings.network),
    }

    if mask_secrets:
        # Mask sensitive values
        if config["llm"].get("litellm_api_key"):
            key = config["llm"]["litellm_api_key"]
            config["llm"]["litellm_api_key"] = key[:4] + "*" * (len(key) - 4)
        if config["network"].get("searxng_api_token"):
            token = config["network"]["searxng_api_token"]
            config["network"]["searxng_api_token"] = token[:4] + "*" * (len(token) - 4)

    return config


def _filter_none_values(d: dict[str, Any]) -> dict[str, Any]:
    """Recursively remove None values from a dictionary."""
    result = {}
    for k, v in d.items():
        if isinstance(v, dict):
            filtered = _filter_none_values(v)
            if filtered:  # Only include non-empty dicts
                result[k] = filtered
        elif v is not None:
            result[k] = v
    return result


def _to_yaml(config: dict[str, Any], with_comments: bool = False) -> str:
    """Convert config dict to YAML string."""
    import yaml

    # Filter out None values for cleaner output
    filtered = _filter_none_values(config)

    if with_comments:
        # Add header comment
        header = """# QuestFoundry Configuration
# ===========================
#
# This file configures the QuestFoundry runtime.
# All values can be overridden via environment variables with QF_ prefix.
#
# Example: runtime.max_iterations -> QF_RUNTIME__MAX_ITERATIONS
#
# For nested values, use double underscore: QF_LLM__OLLAMA_HOST
#

"""
        return header + yaml.dump(
            filtered, default_flow_style=False, sort_keys=False, allow_unicode=True
        )
    else:
        return yaml.dump(
            filtered, default_flow_style=False, sort_keys=False, allow_unicode=True
        )


def _to_toml(config: dict[str, Any]) -> str:
    """Convert config dict to TOML string."""
    try:
        import tomli_w
    except ImportError:
        # Fallback: manual TOML generation for basic types
        return _manual_toml(config)

    # Filter out None values
    filtered = _filter_none_values(config)
    return tomli_w.dumps(filtered)


def _manual_toml(config: dict[str, Any]) -> str:
    """Manual TOML generation when tomli_w is not available."""
    lines = [
        "# QuestFoundry Configuration",
        "# Generated by: qf config init",
        "",
    ]

    for section, values in config.items():
        if not isinstance(values, dict):
            continue

        lines.append(f"[{section}]")
        for key, value in values.items():
            if value is None:
                continue
            if isinstance(value, bool):
                lines.append(f"{key} = {str(value).lower()}")
            elif isinstance(value, str):
                # Escape quotes in strings
                escaped = value.replace("\\", "\\\\").replace('"', '\\"')
                lines.append(f'{key} = "{escaped}"')
            elif isinstance(value, (int, float)):
                lines.append(f"{key} = {value}")
            elif isinstance(value, list):
                # Simple list handling
                items = ", ".join(f'"{v}"' if isinstance(v, str) else str(v) for v in value)
                lines.append(f"{key} = [{items}]")
        lines.append("")

    return "\n".join(lines)


@config_app.command("init")
def config_init(
    output: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help="Output file path (stdout if not specified)",
    ),
    format: str = typer.Option(
        "yaml",
        "--format",
        "-f",
        help="Output format: yaml or toml",
    ),
    minimal: bool = typer.Option(
        False,
        "--minimal",
        "-m",
        help="Only include commonly changed settings",
    ),
):
    """
    Generate a default configuration file.

    Creates a configuration file with all default values that you can
    customize for your project.

    Examples:
        qf config init                      # Print YAML to stdout
        qf config init -o questfoundry.yaml # Write to file
        qf config init -f toml              # Output as TOML
        qf config init --minimal            # Only common settings
    """
    config = _get_default_config()

    if minimal:
        # Only include commonly modified settings
        config = {
            "runtime": {
                "recursion_limit": config["runtime"]["recursion_limit"],
                "max_iterations": config["runtime"]["max_iterations"],
                "debug": config["runtime"]["debug"],
            },
            "llm": {
                "provider": config["llm"]["provider"],
                "default_model": config["llm"]["default_model"],
                "default_temperature": config["llm"]["default_temperature"],
                "ollama_host": config["llm"]["ollama_host"],
            },
            "paths": {
                "project_dir": config["paths"]["project_dir"],
                "project_id": config["paths"]["project_id"],
            },
            "logging": {
                "level": config["logging"]["level"],
            },
        }

    # Generate output
    if format.lower() == "toml":
        content = _to_toml(config)
    else:
        content = _to_yaml(config, with_comments=True)

    # Write output
    if output:
        output.write_text(content, encoding="utf-8")
        console.print(f"[green]Configuration written to:[/green] {output}")
    else:
        print(content)


@config_app.command("dump")
def config_dump(
    output: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help="Output file path (stdout if not specified)",
    ),
    format: str = typer.Option(
        "yaml",
        "--format",
        "-f",
        help="Output format: yaml or toml",
    ),
    show_secrets: bool = typer.Option(
        False,
        "--show-secrets",
        help="Show unmasked secret values (API keys, tokens)",
    ),
):
    """
    Dump current configuration with resolved values.

    Shows the active configuration including values from environment
    variables and config files. Useful for debugging configuration issues.

    Examples:
        qf config dump                        # Print current config
        qf config dump -o current.yaml        # Save to file
        qf config dump --show-secrets         # Include unmasked secrets
    """
    config = _get_current_config(mask_secrets=not show_secrets)

    # Generate output
    if format.lower() == "toml":
        content = _to_toml(config)
    else:
        content = _to_yaml(config, with_comments=False)

    # Write output
    if output:
        output.write_text(content, encoding="utf-8")
        console.print(f"[green]Configuration written to:[/green] {output}")
    else:
        print(content)


@config_app.command("show")
def config_show(
    section: str | None = typer.Argument(
        None,
        help="Configuration section to show (runtime, llm, memory, paths, logging, network)",
    ),
):
    """
    Show current configuration in a readable format.

    Displays the active configuration with nice formatting.
    Optionally filter to a specific section.

    Examples:
        qf config show           # Show all sections
        qf config show llm       # Show only LLM settings
        qf config show runtime   # Show only runtime settings
    """
    from questfoundry.runtime.cli.doctor import format_config_dump

    settings = get_settings()

    if section:
        section = section.lower()
        valid_sections = {"runtime", "llm", "memory", "paths", "logging", "network"}
        if section not in valid_sections:
            console.print(f"[red]Unknown section:[/red] {section}")
            console.print(f"Valid sections: {', '.join(sorted(valid_sections))}")
            raise typer.Exit(1)

        # Show just the requested section
        config = _get_current_config()
        section_config = config.get(section, {})
        console.print(f"\n[bold]{section.title()} Configuration:[/bold]\n")
        for key, value in section_config.items():
            if value is not None:
                console.print(f"  {key}: {value}")
    else:
        # Show all using the doctor format
        console.print("\n[bold]Current Configuration:[/bold]\n")
        console.print(format_config_dump(settings))

    console.print()


@config_app.command("path")
def config_path():
    """
    Show where configuration files are loaded from.

    Displays the search paths for configuration files and indicates
    which files were found and loaded.
    """
    from questfoundry.runtime.config import _find_config_file

    console.print("\n[bold]Configuration File Search Paths:[/bold]\n")

    search_paths = [
        Path.cwd() / "questfoundry.yaml",
        Path.cwd() / "questfoundry.toml",
        Path.cwd() / ".questfoundry.yaml",
        Path.home() / ".config" / "questfoundry" / "config.yaml",
        Path.home() / ".config" / "questfoundry" / "config.toml",
    ]

    found_config = _find_config_file()

    for path in search_paths:
        if path.exists():
            if path == found_config:
                console.print(f"  [green]+[/green] {path} [green](active)[/green]")
            else:
                console.print(f"  [yellow].[/yellow] {path} [dim](exists but shadowed)[/dim]")
        else:
            console.print(f"  [dim]-[/dim] {path}")

    console.print()

    if found_config:
        console.print(f"[bold]Active config file:[/bold] {found_config}")
    else:
        console.print("[dim]No configuration file found. Using defaults + environment.[/dim]")

    # Show .env status
    env_file = Path.cwd() / ".env"
    console.print()
    if env_file.exists():
        console.print(f"[bold].env file:[/bold] {env_file} [green](found)[/green]")
    else:
        console.print("[bold].env file:[/bold] not found in current directory")

    console.print()
