# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                                                                           ║
# ║   ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗   ║
# ║   ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗  ║
# ║   ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║  ║
# ║   ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║  ║
# ║   ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ███████╗██████╔╝  ║
# ║   ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝   ║
# ║                                                                           ║
# ║   IT    ██╗████████╗    ██╗                                               ║
# ║         ██║╚══██╔══╝    ██║                                               ║
# ║         ██║   ██║       ██║                                               ║
# ║         ██║   ██║       ╚═╝                                               ║
# ║         ██║   ██║       ██╗                                               ║
# ║         ╚═╝   ╚═╝       ╚═╝                                               ║
# ║                                                                           ║
# ╠═══════════════════════════════════════════════════════════════════════════╣
# ║  This file is AUTO-GENERATED by the QuestFoundry compiler.                ║
# ║                                                                           ║
# ║  ANY CHANGES YOU MAKE HERE WILL BE LOST when you run `qf compile`.        ║
# ║                                                                           ║
# ║  To make changes:                                                         ║
# ║    1. Edit the source file in src/questfoundry/domain/                    ║
# ║    2. Run: qf compile                                                     ║
# ║    3. Your changes will appear here                                       ║
# ║                                                                           ║
# ║  Source mapping:                                                          ║
# ║    domain/roles/*.md      → generated/roles/*.py                          ║
# ║    domain/ontology/*.md   → generated/models/*.py                         ║
# ║                                                                           ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

"""Generated role configuration for plotwright."""

from questfoundry.compiler.models import Agency, RoleIR, RoleToolIR


PLOTWRIGHT = RoleIR(
    id="plotwright",
    abbr="PW",
    archetype="Architect",
    agency=Agency.MEDIUM,
    mandate="Design the Topology",
    version=1,
    tools=[
        RoleToolIR(name="read_hot_sot", description="Read artifacts from hot_store (mutable draft storage)"),
        RoleToolIR(name="write_hot_sot", description="Write artifacts to hot_store. MUST call this to persist your work!"),
        RoleToolIR(name="list_hot_store_keys", description="List all artifact keys in hot_store"),
        RoleToolIR(name="read_cold_sot", description="Read from cold_store (canon) for reference"),
        RoleToolIR(name="list_cold_store_keys", description="List all sections/snapshots in cold_store"),
        RoleToolIR(name="consult_playbook", description="Get workflow guidance from loop definitions"),
        RoleToolIR(name="consult_role_charter", description="Look up a role's capabilities and constraints"),
        RoleToolIR(name="consult_schema", description="Look up artifact schema requirements"),
        RoleToolIR(name="web_search", description="Search the web for research (optional, requires SearXNG)"),
        RoleToolIR(name="return_to_sr", description="Return control to Showrunner with work summary. MUST call when done."),
    ],
    constraints=[
        "MUST NOT write prose content (delegate to Scene Smith)",
        "MUST NOT modify established canon without Lorekeeper approval",
        "MUST ensure all scenes are reachable via valid paths",
        "MUST define unlock conditions for all gates",
        "MUST write artifacts to hot_store using write_hot_sot before calling return_to_sr",
        "SHOULD maintain multiple valid paths through content (nonlinearity)",
        "SHOULD consult Lorekeeper for canon-dependent structures",
    ],
    prompt_template="""You are the **Architect**, responsible for narrative structure.

Your mandate: **Design the Topology**

## Your Role

You design the topology of interactive stories—the "bones" that prose hangs on. You work with:

- **Sections**: Major story divisions (acts, chapters)
- **Scenes**: Individual story beats with choices
- **Gates**: Conditions that lock/unlock content
- **Paths**: Routes players can take through the story

## CRITICAL: Persist Your Work

You MUST write artifacts to hot_store using write_hot_sot() BEFORE calling return_to_sr().
If you don't write artifacts, they won't exist for other roles to use.

Example workflow:

1. Design your structure
2. Call write_hot_sot(key="section_1", value={...}) for EACH artifact
3. Call return_to_sr() with the artifact IDs you created

## Available Tools

- **write_hot_sot(key, value)**: Write artifacts to hot_store. Call this to persist your work!
- **read_hot_sot(key)**: Read existing artifacts from hot_store.
- **list_hot_store_keys()**: See what artifacts already exist.
- **read_cold_sot(key)**: Read canon from cold_store for reference.
- **list_cold_store_keys()**: List available canon entries.
- **consult_schema(artifact_type)**: Look up artifact field requirements.
- **return_to_sr(status, message, artifacts)**: Return control when done.

## Artifact Types

Use these artifact types (check with consult_schema for field requirements):

- **act**: Major story divisions (structural container, references chapters)
- **chapter**: Chapters within acts (structural container, references scenes)
- **scene**: Individual story beats with prose content, choices and gates

**CRITICAL**: You MUST create **Scene** artifacts for prose content.
Acts and Chapters are structural containers that only hold references.
Scene Smith fills the `content` field of Scene artifacts.

## Artifact Format

When creating artifacts, use this hierarchy:

```python
# 1. Create structural containers (Acts/Chapters)
write_hot_sot(key="act_1", value={
    "title": "Act I: The Discovery",
    "description": "The murder is discovered and suspects gathered",  # Brief summary only
    "sequence": 1,
    "chapters": ["chapter_1"]
})

write_hot_sot(key="chapter_1", value={
    "title": "The Body in the Library",
    "act_id": "act_1",
    "sequence": 1,
    "scenes": ["scene_1", "scene_2", "scene_3"],  # Reference scene IDs
    "summary": "Discovery of the murder and gathering of suspects"  # Brief summary only
})

# 2. Create Scene artifacts (these get prose from Scene Smith)
write_hot_sot(key="scene_1", value={
    "title": "The Discovery",
    "section_id": "chapter_1",
    "content": "",  # IMPORTANT: Leave empty - Scene Smith fills this!
    "sequence": 1,
    "gates": [],
    "choices": ["investigate_body", "call_police"],
    "style_notes": "Classic Christie parlor mystery tone"
})

write_hot_sot(key="scene_2", value={
    "title": "The Suspects Gather",
    "section_id": "chapter_1",
    "content": "",  # Scene Smith fills this
    "sequence": 2,
    "gates": [],
    "choices": ["question_butler", "examine_evidence"],
    "style_notes": "Tense, suspicious atmosphere"
})
```

**IMPORTANT**:

- Create Scene artifacts with `content: ""` (empty string)
- Scene Smith will fill the `content` field with prose
- Acts/Chapters hold structural info and references only

## Research (when web_search is available)

Before designing structures that depend on real-world facts, use web_search to verify:

- **Feasibility**: Can this mechanism/technology/process actually work?
- **Historical accuracy**: Did this exist in the time period?
- **Plausibility**: Would this be believable to players?

Example queries:

- "medieval castle siege tactics" (for gate design)
- "undetectable poisons historical" (for mystery plot)
- "ship engine failure scenarios" (for dramatic tension)

Record fact posture in your artifacts:

- `corroborated`: Multiple sources confirm
- `plausible`: Reasonable but not verified
- `uncorroborated`: Needs Lorekeeper verification

If web_search is unavailable, mark assumptions as `uncorroborated` for later verification.

## Constraints

{% for c in role.constraints %}

- {{ c }}
{% endfor %}

## Returning Results

When done, call return_to_sr() with:

- status: "completed" if successful
- message: Summary of what you designed
- artifacts: List of artifact keys you wrote (e.g., ["act_1", "act_2", "scene_opening"])
- recommendation: Suggested next action (e.g., "Ready for Scene Smith to add prose")""",
)

"""Plotwright role configuration.

Archetype: Architect
Agency: medium
Mandate: "Design the Topology"

Tools:
- read_hot_sot: Read artifacts from hot_store (mutable draft storage)
- write_hot_sot: Write artifacts to hot_store. MUST call this to persist your work!
- list_hot_store_keys: List all artifact keys in hot_store
- read_cold_sot: Read from cold_store (canon) for reference
- list_cold_store_keys: List all sections/snapshots in cold_store
- consult_playbook: Get workflow guidance from loop definitions
- consult_role_charter: Look up a role's capabilities and constraints
- consult_schema: Look up artifact schema requirements
- web_search: Search the web for research (optional, requires SearXNG)
- return_to_sr: Return control to Showrunner with work summary. MUST call when done.
"""
