"""Auto-generated tool parameter schemas from JSON Schema.

DO NOT EDIT THIS FILE DIRECTLY.
Run `uv run python scripts/generate_models.py` to regenerate.

Source schemas: schemas/*.schema.json

These schemas define the parameters for LLM tool calls, ensuring
the tool definitions stay in sync with artifact validation schemas.
"""

from __future__ import annotations

from typing import Any

SUBMIT_DREAM_PARAMS: dict[str, Any] = {
    "properties": {
        "audience": {
            "description": "Target audience (e.g., adult, young adult, all ages, mature)",
            "type": "string",
        },
        "content_notes": {
            "description": "Content advisory notes for inclusions and exclusions",
            "properties": {
                "excludes": {
                    "description": "Content excluded",
                    "items": {"type": "string"},
                    "type": "array",
                },
                "includes": {
                    "description": "Content included",
                    "items": {"type": "string"},
                    "type": "array",
                },
            },
            "type": "object",
        },
        "genre": {"description": "Primary genre", "type": "string"},
        "scope": {
            "properties": {
                "branching_depth": {
                    "description": "Branching complexity (e.g., light, moderate, heavy, extensive)",
                    "type": ["string", "null"],
                },
                "estimated_passages": {"description": "Target scene count", "type": "integer"},
                "estimated_playtime_minutes": {
                    "description": "Target reading time",
                    "type": ["integer", "null"],
                },
                "target_word_count": {"description": "Approximate final length", "type": "integer"},
            },
            "required": ["estimated_passages", "target_word_count"],
            "type": "object",
        },
        "style_notes": {"description": "Style guidance", "type": ["string", "null"]},
        "subgenre": {"description": "Optional genre refinement", "type": ["string", "null"]},
        "themes": {
            "description": "Thematic elements",
            "items": {"type": "string"},
            "type": "array",
        },
        "tone": {"description": "Tone descriptors", "items": {"type": "string"}, "type": "array"},
        "type": {"const": "dream", "description": "Artifact type identifier", "type": "string"},
        "version": {"description": "Schema version number", "type": "integer"},
    },
    "required": ["audience", "genre", "themes", "tone", "type", "version"],
    "type": "object",
}
