"""Auto-generated tool parameter schemas from JSON Schema.

DO NOT EDIT THIS FILE DIRECTLY.
Run `uv run python scripts/generate_models.py` to regenerate.

Source schemas: schemas/*.schema.json

These schemas define the parameters for LLM tool calls, ensuring
the tool definitions stay in sync with artifact validation schemas.
"""

from __future__ import annotations

from typing import Any

SUBMIT_DREAM_PARAMS: dict[str, Any] = {
    "type": "object",
    "properties": {
        "type": {"const": "dream", "type": "string", "description": "Artifact type identifier"},
        "version": {"type": "integer", "description": "Schema version number"},
        "genre": {"type": "string", "description": "Primary genre"},
        "subgenre": {"type": "string", "description": "Optional genre refinement"},
        "tone": {"type": "array", "description": "Tone descriptors", "items": {"type": "string"}},
        "audience": {
            "type": "string",
            "description": "Target audience (e.g., adult, young adult, all ages, mature)",
        },
        "themes": {
            "type": "array",
            "description": "Thematic elements",
            "items": {"type": "string"},
        },
        "style_notes": {"type": "string", "description": "Style guidance"},
        "scope": {
            "type": "object",
            "properties": {
                "target_word_count": {"type": "integer", "description": "Approximate final length"},
                "estimated_passages": {"type": "integer", "description": "Target scene count"},
                "branching_depth": {
                    "type": "string",
                    "description": "Branching complexity (e.g., light, moderate, heavy, extensive)",
                },
                "estimated_playtime_minutes": {
                    "type": "integer",
                    "description": "Target reading time",
                },
            },
            "required": ["target_word_count", "estimated_passages"],
        },
        "content_notes": {
            "type": "object",
            "description": "Content advisory notes for inclusions and exclusions",
            "properties": {
                "includes": {
                    "type": "array",
                    "description": "Content included",
                    "items": {"type": "string"},
                },
                "excludes": {
                    "type": "array",
                    "description": "Content excluded",
                    "items": {"type": "string"},
                },
            },
        },
    },
    "required": ["type", "version", "genre", "tone", "audience", "themes"],
}
