"""Auto-generated tool parameter schemas from JSON Schema.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! DO NOT EDIT THIS FILE DIRECTLY - IT IS AUTO-GENERATED                      !!
!! Source of truth: schemas/*.schema.json                                      !!
!! Run: uv run python scripts/generate_models.py                               !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

SCHEMA-FIRST WORKFLOW:
1. Edit the JSON Schema file (e.g., schemas/dream.schema.json)
2. Run the generator: uv run python scripts/generate_models.py
3. Commit BOTH the schema AND this generated file

These schemas define the parameters for LLM tool calls.
Optional fields (not in "required") are made nullable ([type, "null"]) here
because LLMs may send explicit null. Validation strips nulls before checking.
"""

from __future__ import annotations

from typing import Any

SUBMIT_DREAM_PARAMS: dict[str, Any] = {
    "properties": {
        "audience": {
            "description": "Target audience (e.g., adult, young adult, all ages, mature)",
            "type": "string",
        },
        "content_notes": {
            "description": "Content advisory notes for inclusions and exclusions",
            "properties": {
                "excludes": {
                    "description": "Content excluded",
                    "items": {"type": "string"},
                    "type": "array",
                },
                "includes": {
                    "description": "Content included",
                    "items": {"type": "string"},
                    "type": "array",
                },
            },
            "type": "object",
        },
        "genre": {"description": "Primary genre", "type": "string"},
        "scope": {
            "properties": {
                "branching_depth": {
                    "description": "Branching complexity (e.g., light, moderate, heavy, extensive)",
                    "type": ["string", "null"],
                },
                "estimated_passages": {"description": "Target scene count", "type": "integer"},
                "estimated_playtime_minutes": {
                    "description": "Target reading time",
                    "type": ["integer", "null"],
                },
                "target_word_count": {"description": "Approximate final length", "type": "integer"},
            },
            "required": ["estimated_passages", "target_word_count"],
            "type": "object",
        },
        "style_notes": {"description": "Style guidance", "type": ["string", "null"]},
        "subgenre": {"description": "Optional genre refinement", "type": ["string", "null"]},
        "themes": {
            "description": "Thematic elements",
            "items": {"type": "string"},
            "type": "array",
        },
        "tone": {"description": "Tone descriptors", "items": {"type": "string"}, "type": "array"},
        "type": {"const": "dream", "description": "Artifact type identifier", "type": "string"},
        "version": {"description": "Schema version number", "type": "integer"},
    },
    "required": ["audience", "genre", "themes", "tone", "type", "version"],
    "type": "object",
}
