# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                                                                           ║
# ║   ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗   ║
# ║   ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗  ║
# ║   ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║  ║
# ║   ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║  ║
# ║   ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ███████╗██████╔╝  ║
# ║   ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝   ║
# ║                                                                           ║
# ║   IT    ██╗████████╗    ██╗                                               ║
# ║         ██║╚══██╔══╝    ██║                                               ║
# ║         ██║   ██║       ██║                                               ║
# ║         ██║   ██║       ╚═╝                                               ║
# ║         ██║   ██║       ██╗                                               ║
# ║         ╚═╝   ╚═╝       ╚═╝                                               ║
# ║                                                                           ║
# ╠═══════════════════════════════════════════════════════════════════════════╣
# ║  This file is AUTO-GENERATED by the QuestFoundry compiler.                ║
# ║                                                                           ║
# ║  ANY CHANGES YOU MAKE HERE WILL BE LOST when you run `qf compile`.        ║
# ║                                                                           ║
# ║  To make changes:                                                         ║
# ║    1. Edit the source file in src/questfoundry/domain/                    ║
# ║    2. Run: qf compile                                                     ║
# ║    3. Your changes will appear here                                       ║
# ║                                                                           ║
# ║  Source mapping:                                                          ║
# ║    domain/roles/*.md      → generated/roles/*.py                          ║
# ║    domain/ontology/*.md   → generated/models/*.py                         ║
# ║                                                                           ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
"""Generated loop definitions.

These LoopIR objects are generated from MyST domain files in domain/loops/.
They define workflow patterns for the orchestration system.

Usage:
    from questfoundry.generated.loops import ALL_LOOPS

    loop = ALL_LOOPS['story_spark']
"""

from questfoundry.compiler.models import (
    GraphEdgeIR,
    GraphNodeIR,
    LoopIR,
    QualityGateIR,
)

# =============================================================================
# canon_commit
# =============================================================================

CANON_COMMIT = LoopIR(
    id="canon_commit",
    name="Canon Commit",
    trigger="gatecheck_passed",
    entry_point="showrunner",
    nodes=[
        GraphNodeIR(
            id="showrunner",
            role="showrunner",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="lorekeeper",
            role="lorekeeper",
            timeout=600,
            max_iterations=10,
        ),
        GraphNodeIR(
            id="gatekeeper",
            role="gatekeeper",
            timeout=300,
            max_iterations=3,
        ),
    ],
    edges=[
        GraphEdgeIR(
            source="showrunner",
            target="lorekeeper",
            condition="intent.status == 'merge_authorized'",
        ),
        GraphEdgeIR(
            source="showrunner",
            target="END",
            condition="intent.type == 'terminate'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="gatekeeper",
            condition="intent.status == 'merge_prepared'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="lorekeeper",
            condition="intent.status == 'failed'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="showrunner",
            condition="intent.status == 'passed'",
        ),
    ],
    quality_gates=[
        QualityGateIR(
            before="gatekeeper",
            role="gatekeeper",
            bars=["integrity", "presentation"],
            blocking=True,
        ),
    ],
)

# =============================================================================
# codex_expansion
# =============================================================================

CODEX_EXPANSION = LoopIR(
    id="codex_expansion",
    name="Codex Expansion",
    trigger="canon_available",
    entry_point="showrunner",
    nodes=[
        GraphNodeIR(
            id="showrunner",
            role="showrunner",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="lorekeeper",
            role="lorekeeper",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="creative_director",
            role="creative_director",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="gatekeeper",
            role="gatekeeper",
            timeout=300,
            max_iterations=3,
        ),
    ],
    edges=[
        GraphEdgeIR(
            source="showrunner",
            target="lorekeeper",
            condition="intent.status == 'brief_created'",
        ),
        GraphEdgeIR(
            source="showrunner",
            target="END",
            condition="intent.type == 'terminate'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="creative_director",
            condition="intent.status == 'entries_drafted'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
        GraphEdgeIR(
            source="creative_director",
            target="gatekeeper",
            condition="intent.status == 'style_approved'",
        ),
        GraphEdgeIR(
            source="creative_director",
            target="lorekeeper",
            condition="intent.status == 'needs_revision'",
        ),
        GraphEdgeIR(
            source="creative_director",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="lorekeeper",
            condition="intent.status == 'failed'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="showrunner",
            condition="intent.status == 'passed'",
        ),
    ],
    quality_gates=[
        QualityGateIR(
            before="gatekeeper",
            role="gatekeeper",
            bars=["presentation", "integrity", "style"],
            blocking=True,
        ),
    ],
)

# =============================================================================
# hook_harvest
# =============================================================================

HOOK_HARVEST = LoopIR(
    id="hook_harvest",
    name="Hook Harvest",
    trigger="backlog_review",
    entry_point="showrunner",
    nodes=[
        GraphNodeIR(
            id="showrunner",
            role="showrunner",
            timeout=600,
            max_iterations=10,
        ),
        GraphNodeIR(
            id="lorekeeper",
            role="lorekeeper",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="plotwright",
            role="plotwright",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="gatekeeper",
            role="gatekeeper",
            timeout=300,
            max_iterations=3,
        ),
    ],
    edges=[
        GraphEdgeIR(
            source="showrunner",
            target="lorekeeper",
            condition="intent.status == 'needs_canon_check'",
        ),
        GraphEdgeIR(
            source="showrunner",
            target="plotwright",
            condition="intent.status == 'needs_structure_check'",
        ),
        GraphEdgeIR(
            source="showrunner",
            target="gatekeeper",
            condition="intent.status == 'harvest_complete'",
        ),
        GraphEdgeIR(
            source="showrunner",
            target="END",
            condition="intent.type == 'terminate'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="showrunner",
            condition="intent.status == 'canon_assessed'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
        GraphEdgeIR(
            source="plotwright",
            target="showrunner",
            condition="intent.status == 'structure_assessed'",
        ),
        GraphEdgeIR(
            source="plotwright",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="showrunner",
            condition="intent.status == 'passed'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="showrunner",
            condition="intent.status == 'failed'",
        ),
    ],
    quality_gates=[
        QualityGateIR(
            before="END",
            role="gatekeeper",
            bars=["integrity"],
            blocking=False,
        ),
    ],
)

# =============================================================================
# lore_deepening
# =============================================================================

LORE_DEEPENING = LoopIR(
    id="lore_deepening",
    name="Lore Deepening",
    trigger="hooks_accepted",
    entry_point="showrunner",
    nodes=[
        GraphNodeIR(
            id="showrunner",
            role="showrunner",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="lorekeeper",
            role="lorekeeper",
            timeout=900,
            max_iterations=15,
        ),
        GraphNodeIR(
            id="plotwright",
            role="plotwright",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="gatekeeper",
            role="gatekeeper",
            timeout=300,
            max_iterations=3,
        ),
    ],
    edges=[
        GraphEdgeIR(
            source="showrunner",
            target="lorekeeper",
            condition="intent.status == 'brief_created'",
        ),
        GraphEdgeIR(
            source="showrunner",
            target="END",
            condition="intent.type == 'terminate'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="plotwright",
            condition="intent.status == 'needs_topology_check'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="gatekeeper",
            condition="intent.status == 'canon_drafted'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
        GraphEdgeIR(
            source="plotwright",
            target="lorekeeper",
            condition="intent.status == 'topology_assessed'",
        ),
        GraphEdgeIR(
            source="plotwright",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="lorekeeper",
            condition="intent.status == 'failed'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="showrunner",
            condition="intent.status == 'passed'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="showrunner",
            condition="intent.status == 'waiver_requested'",
        ),
    ],
    quality_gates=[
        QualityGateIR(
            before="gatekeeper",
            role="gatekeeper",
            bars=["integrity", "gateways"],
            blocking=True,
        ),
    ],
)

# =============================================================================
# scene_weave
# =============================================================================

SCENE_WEAVE = LoopIR(
    id="scene_weave",
    name="Scene Weave",
    trigger="topology_ready",
    entry_point="showrunner",
    nodes=[
        GraphNodeIR(
            id="showrunner",
            role="showrunner",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="scene_smith",
            role="scene_smith",
            timeout=900,
            max_iterations=15,
        ),
        GraphNodeIR(
            id="creative_director",
            role="creative_director",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="lorekeeper",
            role="lorekeeper",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="gatekeeper",
            role="gatekeeper",
            timeout=300,
            max_iterations=3,
        ),
    ],
    edges=[
        GraphEdgeIR(
            source="showrunner",
            target="scene_smith",
            condition="intent.status == 'brief_created'",
        ),
        GraphEdgeIR(
            source="showrunner",
            target="END",
            condition="intent.type == 'terminate'",
        ),
        GraphEdgeIR(
            source="scene_smith",
            target="lorekeeper",
            condition="intent.status == 'needs_canon'",
        ),
        GraphEdgeIR(
            source="scene_smith",
            target="creative_director",
            condition="intent.status == 'needs_style_check'",
        ),
        GraphEdgeIR(
            source="scene_smith",
            target="gatekeeper",
            condition="intent.status == 'draft_complete'",
        ),
        GraphEdgeIR(
            source="scene_smith",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="scene_smith",
            condition="intent.status == 'canon_provided'",
        ),
        GraphEdgeIR(
            source="creative_director",
            target="scene_smith",
            condition="intent.status == 'style_guidance_provided'",
        ),
        GraphEdgeIR(
            source="creative_director",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="scene_smith",
            condition="intent.status == 'failed'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="showrunner",
            condition="intent.status == 'passed'",
        ),
    ],
    quality_gates=[
        QualityGateIR(
            before="gatekeeper",
            role="gatekeeper",
            bars=["style", "presentation", "accessibility"],
            blocking=True,
        ),
    ],
)

# =============================================================================
# story_spark
# =============================================================================

STORY_SPARK = LoopIR(
    id="story_spark",
    name="Story Spark",
    trigger="user_request",
    entry_point="showrunner",
    nodes=[
        GraphNodeIR(
            id="showrunner",
            role="showrunner",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="plotwright",
            role="plotwright",
            timeout=600,
            max_iterations=10,
        ),
        GraphNodeIR(
            id="lorekeeper",
            role="lorekeeper",
            timeout=300,
            max_iterations=5,
        ),
        GraphNodeIR(
            id="gatekeeper",
            role="gatekeeper",
            timeout=300,
            max_iterations=3,
        ),
        GraphNodeIR(
            id="scene_smith",
            role="scene_smith",
            timeout=900,
            max_iterations=15,
        ),
    ],
    edges=[
        GraphEdgeIR(
            source="showrunner",
            target="plotwright",
            condition="intent.status == 'brief_created'",
        ),
        GraphEdgeIR(
            source="showrunner",
            target="END",
            condition="intent.type == 'terminate'",
        ),
        GraphEdgeIR(
            source="plotwright",
            target="lorekeeper",
            condition="intent.status == 'needs_lore'",
        ),
        GraphEdgeIR(
            source="plotwright",
            target="gatekeeper",
            condition="intent.status == 'topology_complete'",
        ),
        GraphEdgeIR(
            source="plotwright",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="plotwright",
            condition="intent.status == 'lore_verified'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="scene_smith",
            condition="intent.status == 'canon_provided'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="showrunner",
            condition="intent.status == 'promoted_to_canon'",
        ),
        GraphEdgeIR(
            source="lorekeeper",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="plotwright",
            condition="intent.status == 'topology_failed'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="scene_smith",
            condition="intent.status == 'topology_passed'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="scene_smith",
            condition="intent.status == 'prose_failed'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="lorekeeper",
            condition="intent.status == 'prose_passed'",
        ),
        GraphEdgeIR(
            source="gatekeeper",
            target="showrunner",
            condition="intent.status == 'waiver_requested'",
        ),
        GraphEdgeIR(
            source="scene_smith",
            target="gatekeeper",
            condition="intent.status == 'prose_complete'",
        ),
        GraphEdgeIR(
            source="scene_smith",
            target="lorekeeper",
            condition="intent.status == 'needs_canon'",
        ),
        GraphEdgeIR(
            source="scene_smith",
            target="showrunner",
            condition="intent.type == 'escalation'",
        ),
    ],
    quality_gates=[
        QualityGateIR(
            before="gatekeeper",
            role="gatekeeper",
            bars=["reachability", "nonlinearity", "gateways"],
            blocking=True,
        ),
        QualityGateIR(
            before="lorekeeper",
            role="gatekeeper",
            bars=["style", "presentation"],
            blocking=True,
        ),
    ],
)

# =============================================================================
# Registry
# =============================================================================

ALL_LOOPS: dict[str, LoopIR] = {
    "canon_commit": CANON_COMMIT,
    "codex_expansion": CODEX_EXPANSION,
    "hook_harvest": HOOK_HARVEST,
    "lore_deepening": LORE_DEEPENING,
    "scene_weave": SCENE_WEAVE,
    "story_spark": STORY_SPARK,
}

__all__ = [
    "ALL_LOOPS",
    "CANON_COMMIT",
    "CODEX_EXPANSION",
    "HOOK_HARVEST",
    "LORE_DEEPENING",
    "SCENE_WEAVE",
    "STORY_SPARK",
]
